### ISSUE TITLE
4D Tools "Center of Mass 4D" broken?

### ISSUE THREAD

**Issue by TomaSusi** [nion-software/experimental#25]
Hi,

Having installed a fresh conda environment with Nion Swift and the nionswift-experimental tools, I tried to use the 4D Tools "Center of Mass 4D" to calculate the CoM from an old 4D dataset. However, I get an empty data item and this gets printed in the console – there seem to be two issues:

```
module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Traceback (most recent call last):
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nionswift_plugin/nion_experimental_4dtools/CenterOfMass4D.py", line 66, in execute
    mask_data = np.zeros(src_data_item.xdata.data_shape[2:], dtype=np.bool)
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
Traceback (most recent call last):
File "/Users/tomasusi/miniconda3/envs/nionswift/bin/Nion Swift.app/Contents/MacOS/../Resources/bootstrap.py", line 25, in bootstrap_dispatch
return getattr(object, method_name)(*args)
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/ui/QtUserInterface.py", line 2053, in periodic
self._handle_periodic()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/ui/UserInterface.py", line 3478, in _handle_periodic
self.on_periodic()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/swift/DocumentController.py", line 378, in periodic
super().periodic()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/ui/Window.py", line 370, in periodic
self.__periodic_queue.perform_tasks()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/utils/Process.py", line 36, in perform_tasks
task()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/swift/DocumentController.py", line 182, in call_soon
self.document_model.perform_call_soon()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/swift/model/DocumentModel.py", line 780, in perform_call_soon
fn()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/swift/model/DocumentModel.py", line 1627, in commit_pending_computation
pending_computation_executor.commit()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/swift/model/Symbolic.py", line 2051, in commit
self._commit()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nion/swift/model/Symbolic.py", line 2178, in _commit
self.__computation_handler.commit()
File "/Users/tomasusi/miniconda3/envs/nionswift/lib/python3.10/site-packages/nionswift_plugin/nion_experimental_4dtools/CenterOfMass4D.py", line 102, in commit
self.computation.set_referenced_xdata('target', self.__new_xdata)
AttributeError
:
'CenterOfMass4D' object has no attribute '_CenterOfMass4D__new_xdata'
. Did you mean: '
_CenterOfMass4D__api
'?
```

I am on macOS 13.1 and the conda environment is (by default) 3.10.10.

Cheers,
Toma

**Comment by TomaSusi** [comment]
Not sure if these tools are still supported? :) @Brow71189

**Comment by Brow71189** [comment]
This is actually fixed in the master branch: https://github.com/nion-software/experimental/blob/5fdcb9c11e2a3cdc248c5ff89e14d910812a728c/nionswift_plugin/nion_experimental_4dtools/CenterOfMass4D.py#L78
But we haven't done a release yet, so we should definitely do that soon.

In the meantime you can install the package generated from the latest build: https://github.com/nion-software/experimental/actions/runs/3933442280
 
Scroll down to the bottom, click on the "distribution" link under "Artifacts" to download the build. Unzip the file and install the containing "*.whl" package with "pip install nionswift_experimental-0.7.9-py3-none-any.whl".
You should probably also uninstall the conda installed experimental package first.
